spring:
  application:
    name: store-ecom
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: info
server:
  error:
    include-stacktrace: never
